<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rdBtn_none</name>
   <tag></tag>
   <elementGuidId>56f4b99c-d39d-4ee7-aec7-9e161caa08fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'radio_program_none']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio_program_none</value>
      <webElementGuid>dbb20def-9e88-4cb6-9ff9-ee21f3a64b69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@id='radio_program_none']</value>
      <webElementGuid>49f5a260-1677-470b-8c34-ed43d39aa809</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
